server:
  port: 8028
############################################
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8020/eureka,http://localhost:8021/eureka
############################################
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #服务路由方式一:gateway自动配置
          #true，表明Gateway开启服务注册和发现的功能，并且Spring Cloud Gateway自动根据服务
          # 发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
          enabled: true
          #将请求路径上的服务名配置为小写 【因为服务注册的时候，向注册中心注册时将服务名转成大写的了】
          lower-case-service-id: true


